'use server';

import { signIn } from "../../../auth";
import { AuthError } from "next-auth";

export async function authenticate(
    prevState: string | undefined,
    formData: FormData,
) {
    try {
        return await signIn('credentials', formData);
    } catch (err) {
        if (err instanceof AuthError) {
            switch (err.type) {
                case 'CredentialsSignin':
                    return 'Credenciais inv√°lidas.';
                default:
                    return 'Aconteceu um erro interno.';
            }
        }

        throw err;
    }
}